name: Build and Deploy
on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-docs
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Dependencies
        run: |
          .github/workflows/dependencies/documentation.sh
          echo "Installing python packages for docs..."
          python3 -m pip install --upgrade pip
          python3 -m pip install sphinx sphinx_rtd_theme breathe sphinxcontrib.bibtex docutils

      - name: Install and Build
        run: |
          cd Docs
          echo "Build the Sphinx documentation for amrex-tutorials."
          make latexpdf
          mv build/latex/amrex.pdf source/
          make html

      - name: Deploy
        if: github.event_name == 'push' && github.repository == 'WeiqunZhang/amrex-tutorials' && github.ref == 'refs/heads/deploy'
        run: |
          ls Docs/
          ls Docs/build
          ls Docs/build/html
          DEPLOY_SOURCE=${PWD}/Docs/build/html
          DEPLOY_SOURCE_HEAD=`git rev-parse --short HEAD`

          cd ..

          # Configure SSH client

          git config -l
          git config user.name WeiqunZhang
          git config user.email WeiqunZhang@lbl.gov
          git config core.ignorecase false
          git clone git@github.com:AMReX-Codes/AMReX-Codes.github.io
          cd AMReX-Codes.github.io/amrex/tutorials_html/
          ls
          ls ${DEPLOY_SOUrCE}


